title: George Lepskas Blog
author: George Lepska
email: your.email@example.com # optional

# Build settings
theme: minima
permalink: /:year/:month/:day/:title/

# Minima specific settings
minima:
  skin: dark # options: classic, dark, auto, solarized-light, solarized-dark
  
# Social links (optional - remove # to enable)
# github_username: GeorgeLepska
# instagram_username: your_instagram
# linkedin_username: your_linkedin



# Google Analytics (optional)
# google_analytics: UA-NNNNNNNN-N

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
